name: typedKanren
version: 0.1.0.0
github: "SnejUgal/typedKanren"
license: BSD-3-Clause
author: "Author name here"
maintainer: "example@example.com"
copyright: "2023 Author name here"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

description: Please see the README on GitHub at <https://github.com/SnejUgal/typedKanren#readme>

dependencies:
  - base >= 4.7 && < 5
  - containers
  - template-haskell
  - lens
  - bifunctors
  - tagged
  - deepseq
  - strict-list

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  example:
    main: Main.hs
    source-dirs: example
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - typedKanren

tests:
  typedKanren-tests:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - typedKanren
      - hspec
      - QuickCheck

benchmarks:
  bench:
    main: Main.hs
    source-dirs: bench
    ghc-options:
      - -threaded
      - -O2
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - typedKanren
      - criterion
      - deepseq
